---
- hosts: webserver
  become: yes
  tasks:
   - name: install utlities
     apt: 
      name: "{{ item }}"
     with_items:
     - tree
     - git
     - nano
     when: ansible_os_family == "Debian"