---
- hosts: webserver
  become: yes
  tasks:
   - name: package update
     apt: 
      update_cache: yes

   - name: install apache2
     apt:
        name: apache2
        state: present
   - name: creating the homepage
     copy:
      dest: /var/www/html/index.html
      content: "<h1>welcome to ansible(controlled by acs)</h1>"
  