---
- hosts: webserver
  become: yes
  tasks:
   - name: package update
     apt: 
      update_cache: yes

   - name: install apache2
     apt:
        name: apache2
        state: present
   - name: creating the homepage
     file:
      path: /home/ansible/index.html
      state: file
   - name: stop apache2
     apt:
      name: apache2
      state: stopped
   - name: create index homepage
     file:
      src: /home/ansible/index.html
      dest: /var/www/html/index.html

   - name: start apache2
     apt:
      name: apache2
      state: started   
